import { expect, test, type Page } from '@playwright/test'
import { EMPRESA_CARTEIRA_PRIVADA } from './dados-carteira-visual'

async function entrar(page: Page) {
  await page.goto('/login')
  await page.getByLabel('E-mail').fill('carteiravisuale2e@teste.local')
  await page.getByLabel('Senha', { exact: true }).fill('Senha-e2e-2026')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL('/meu-dia')
  await page.goto('/carteira')
}

async function conferirTamanhos(page: Page, tela: string) {
  for (const tema of ['light', 'dark']) {
    await page.getByRole('combobox', { name: /Tema/ }).selectOption(tema)
    for (const width of [390, 820, 1280]) {
      await page.setViewportSize({ width, height: 844 })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await page.screenshot({ path: `test-results/carteira-${tela}-${tema}-${width}.png`, fullPage: true })
    }
  }
}

async function voltarNoNavegador(page: Page) {
  await page.evaluate(() => new Promise<void>(resolve => {
    window.addEventListener('popstate', () => {
      requestAnimationFrame(() => requestAnimationFrame(() => resolve()))
    }, { once: true })
    window.history.back()
  }))
}

test('carteira filtra cards, conserva filtros na ficha e protege dados de outro vendedor', async ({ page }) => {
  await entrar(page)
  await expect(page.getByRole('link', { name: 'Ver cliente', exact: true })).toHaveCount(2)
  await expect(page.getByRole('main')).toContainText('2 de 2 empresas')
  await expect(page.getByText(/^Nota inicial Aurora /)).toBeVisible()
  await expect(page.getByText('Nota inicial Boreal', { exact: true })).toBeVisible()
  await expect(page.getByRole('main')).not.toContainText('Carteira Visual Privada')
  await conferirTamanhos(page, 'cards')

  await page.getByLabel('Nome', { exact: true }).fill('Aurora')
  await page.getByLabel('UF', { exact: true }).selectOption('SP')
  await page.getByLabel('Retorno', { exact: true }).selectOption('atrasado')
  await page.getByRole('button', { name: 'Filtrar', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Ver cliente', exact: true })).toHaveCount(1)
  await expect(page.getByRole('main')).toContainText('1 de 2 empresas')
  const filtros = new URL(page.url()).search
  await page.getByRole('link', { name: 'Ver cliente', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Carteira Visual Aurora', exact: true })).toBeVisible()
  expect(new URL(page.url()).search).toBe(filtros)
  await expect(page.getByText(`Nota inicial Aurora ${'x'.repeat(300)}`, { exact: true })).toBeVisible()
  await conferirTamanhos(page, 'ficha')
  await page.getByRole('link', { name: /Voltar.*carteira/i }).click()
  await expect(page).toHaveURL(`/carteira${filtros}`)
  await page.getByLabel('Nome', { exact: true }).fill('')
  await page.getByLabel('UF', { exact: true }).selectOption('RJ')
  await page.getByLabel('Retorno', { exact: true }).selectOption('sem_data')
  await page.getByRole('button', { name: 'Filtrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Carteira Visual Boreal', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Carteira Visual Aurora', exact: true })).toHaveCount(0)
  await page.goto(`/carteira/${EMPRESA_CARTEIRA_PRIVADA}`)
  await expect(page.locator('body')).toContainText('404')
  await expect(page.locator('body')).not.toContainText('Nota privada de outro vendedor')
  await expect(page.locator('body')).not.toContainText('Retorno privado')
  await expect(page.getByRole('heading', { name: 'Carteira Visual Privada', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Registrar atendimento', exact: true })).toHaveCount(0)
})

test('ficha preserva rascunho e erro, confirma descarte, atualiza atendimento e devolve', async ({ page }) => {
  test.setTimeout(60_000)
  await entrar(page)
  await page.getByRole('listitem').filter({ has: page.getByRole('heading', { name: 'Carteira Visual Boreal', exact: true }) })
    .getByRole('link', { name: 'Ver cliente', exact: true }).click()
  await expect(page).toHaveURL(/\/carteira\/[0-9a-f-]+$/)
  const fichaUrl = page.url()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Registrar atendimento', exact: true }).click()
  await page.getByLabel('Nota', { exact: true }).fill('Rascunho que deve sobreviver')
  await page.getByLabel('Próximo passo', { exact: true }).fill('Enviar proposta revisada')
  await page.getByRole('button', { name: 'Registrar', exact: true }).click()
  await expect(page.getByText('Próximo passo e data andam juntos: preencha os dois ou nenhum.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('Rascunho que deve sobreviver')
  await conferirTamanhos(page, 'editor')
  await page.getByRole('link', { name: /Voltar.*carteira/i }).click()
  const dialogo = page.getByRole('dialog')
  await expect(dialogo).toBeVisible()
  await dialogo.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('Rascunho que deve sobreviver')
  await page.getByRole('link', { name: /Voltar.*carteira/i }).click()
  await dialogo.getByRole('button', { name: 'Descartar e continuar', exact: true }).click()
  await expect(page).toHaveURL('/carteira')
  await page.goto(fichaUrl)
  await page.getByRole('button', { name: 'Registrar atendimento', exact: true }).click()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('')
  await page.getByLabel('Nota', { exact: true }).fill('Atendimento salvo pela ficha real')
  await page.getByLabel('Próximo passo', { exact: true }).fill('Enviar proposta revisada')
  await page.getByLabel('Data do próximo passo', { exact: true }).fill('2030-10-01')
  let liberarEnvio!: () => void
  const envioLiberado = new Promise<void>(resolve => { liberarEnvio = resolve })
  await page.route('**/carteira/**', async route => {
    if (route.request().method() === 'POST') await envioLiberado
    await route.continue()
  })
  await page.getByRole('button', { name: 'Registrar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Cancelar atendimento', exact: true })).toBeDisabled()
  await voltarNoNavegador(page)
  await expect(page).toHaveURL(fichaUrl)
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('Atendimento salvo pela ficha real')
  await expect(page.getByRole('button', { name: 'Cancelar atendimento', exact: true })).toBeDisabled()
  liberarEnvio()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveCount(0)
  await page.unroute('**/carteira/**')
  await expect(page.getByText('Atendimento salvo pela ficha real', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Atendimento salvo pela ficha real', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Registrar atendimento', exact: true }).click()
  await page.getByLabel('Nota', { exact: true }).fill('Devolução registrada pela ficha real')
  await page.getByLabel('Próximo passo', { exact: true }).fill('Retorno registrado no histórico')
  await page.getByLabel('Data do próximo passo', { exact: true }).fill('2030-10-02')
  await page.getByRole('button', { name: 'Registrar e devolver', exact: true }).click()
  await expect(page).toHaveURL('/carteira')
  await expect(page.getByRole('heading', { name: 'Carteira Visual Boreal', exact: true })).toHaveCount(0)
  await page.goto(fichaUrl)
  await expect(page.getByRole('button', { name: 'Registrar atendimento', exact: true })).toHaveCount(0)
  await expect(page.locator('body')).toContainText('404')
  await expect(page.locator('body')).not.toContainText('Devolução registrada pela ficha real')
})

test('Voltar do navegador pede confirmação e cancelar mantém o rascunho', async ({ page }) => {
  await entrar(page)
  await page.getByRole('listitem').filter({ has: page.getByRole('heading', { name: 'Carteira Visual Aurora', exact: true }) })
    .getByRole('link', { name: 'Ver cliente', exact: true }).click()
  await expect(page).toHaveURL(/\/carteira\/[0-9a-f-]+$/)
  const fichaUrl = page.url()
  await page.getByRole('button', { name: 'Registrar atendimento', exact: true }).click()
  await page.getByLabel('Nota', { exact: true }).fill('Rascunho protegido no histórico real')
  await voltarNoNavegador(page)
  const dialogo = page.getByRole('dialog')
  await expect(dialogo).toBeVisible()
  await dialogo.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page).toHaveURL(fichaUrl)
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('Rascunho protegido no histórico real')
  await voltarNoNavegador(page)
  await expect(dialogo).toBeVisible()
  await dialogo.getByRole('button', { name: 'Descartar e continuar', exact: true }).click()
  await expect(page).toHaveURL('/carteira')
  await page.evaluate(() => window.history.forward())
  await expect(page).toHaveURL(fichaUrl)
  await expect(page.getByRole('button', { name: 'Registrar atendimento', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
