import { expect, test, type Page } from '@playwright/test'

async function entrar(page: Page, papel: 'gestor' | 'vendedor') {
  await page.goto('/login')
  await page.getByLabel('E-mail').fill(`${papel}e2e@teste.local`)
  await page.getByLabel('Senha', { exact: true }).fill('Senha-e2e-2026')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL('/')
}

test('galeria exige sessão de gestor', async ({ page }) => {
  await page.goto('/design')
  await expect(page).toHaveURL('/login')
  await entrar(page, 'vendedor')
  await page.goto('/design')
  await expect(page).toHaveURL('/')
})

test('gestor acessa a galeria', async ({ page }) => {
  await entrar(page, 'gestor')
  await page.goto('/design')
  await expect(page.locator('main')).toBeVisible()
  await expect(page.locator('.crm-ui').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Abrir menu', exact: true })).not.toBeVisible()
  await expect(page.getByText('Ausente', { exact: true })).not.toBeVisible()
  const botoes = page.locator('[data-testid="company-list"] button')
  const posicoes = await botoes.evaluateAll((elementos) => elementos.map((elemento) => elemento.getBoundingClientRect().bottom))
  expect(Math.max(...posicoes) - Math.min(...posicoes)).toBeLessThan(2)
})

test('temas e navegação preservam o texto sem chamadas de escrita', async ({ page }) => {
  await entrar(page, 'gestor')
  await page.goto('/design')
  const escritas: string[] = []
  page.on('request', (request) => {
    if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method())) escritas.push(request.url())
  })
  const tema = page.getByLabel('Tema da galeria')
  await tema.selectOption('light')
  await expect(page.locator('.crm-ui').first()).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('.crm-ui').first()).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.screenshot({ path: 'test-results/galeria-clara.png', fullPage: true })
  await tema.selectOption('dark')
  await expect(page.locator('.crm-ui').first()).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.crm-ui').first()).toHaveCSS('background-color', 'rgb(9, 9, 11)')
  await page.screenshot({ path: 'test-results/galeria-escura.png', fullPage: true })
  await tema.selectOption('system')
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('.crm-ui').first()).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('.crm-ui').first()).toHaveCSS('background-color', 'rgb(9, 9, 11)')
  await page.getByRole('button', { name: 'Buscar cliente', exact: true }).click()
  await expect(page.getByText('Etapa atual: Consultar', { exact: true })).toBeVisible()
  const anotacoes = page.getByLabel('Anotações da ligação', { exact: true })
  await anotacoes.fill('Conversar com a responsável na sexta de manhã')
  await page.getByRole('button', { name: 'Registrar resultado', exact: true }).click()
  await expect(page.getByText('Etapa atual: Registrar', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Voltar', exact: true }).click()
  await expect(anotacoes).toHaveValue('Conversar com a responsável na sexta de manhã')
  expect(escritas).toEqual([])
})

test('galeria cabe em celular de 390px', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await entrar(page, 'gestor')
  await page.goto('/design')
  await page.getByLabel('Tema da galeria').selectOption('light')
  await expect(page.locator('main')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/galeria-mobile.png', fullPage: true })
  const menu = page.getByRole('button', { name: 'Abrir menu', exact: true })
  await menu.click()
  await expect(menu).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('link', { name: 'Filtros', exact: true }).click()
  await expect(menu).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('link', { name: 'Filtros', exact: true })).not.toBeVisible()
  await page.setViewportSize({ width: 1000, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('filtros mostram estado vazio e restauram os exemplos', async ({ page }) => {
  await entrar(page, 'gestor')
  await page.goto('/design')
  await expect(page.getByLabel('CNAE', { exact: true })).toHaveJSProperty('tagName', 'SELECT')
  await page.getByLabel('Nome da empresa', { exact: true }).fill('Sem correspondência')
  await page.getByRole('button', { name: 'Aplicar filtros', exact: true }).click()
  await expect(page.getByText('Nenhuma empresa encontrada', { exact: true })).toBeVisible()
  await expect(page.getByTestId('company-list').getByText('Aurora Papelaria Ltda.', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Limpar filtros', exact: true }).click()
  await expect(page.getByTestId('company-list').getByText('Aurora Papelaria Ltda.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Nome da empresa', { exact: true })).toBeEmpty()
  const card = page.locator('[data-slot="card"]').filter({ hasText: 'Café Cedro Comércio Ltda.' })
  await card.getByRole('button', { name: 'Ver exemplo', exact: true }).click()
  await expect(card.getByText('Telefone fictício', { exact: false })).toBeVisible()
  const nota = page.getByLabel('Anotações da tentativa', { exact: true })
  await nota.fill('Anotação preservada mesmo com reserva expirada')
  await expect(nota).toHaveValue('Anotação preservada mesmo com reserva expirada')
})

test('diálogo mantém tema e foco, fecha com Escape e retorna ao acionador', async ({ page }) => {
  await entrar(page, 'gestor')
  await page.goto('/design')
  await page.getByLabel('Tema da galeria').selectOption('dark')
  const abrir = page.getByRole('button', { name: 'Próxima', exact: true })
  await abrir.click()
  const dialogo = page.getByRole('dialog', { name: 'Trocar de empresa e descartar as anotações?' })
  await expect(dialogo).toBeVisible()
  await expect(page.locator('.ui-dialog-portal')).toHaveAttribute('data-theme', 'dark')
  expect(await dialogo.evaluate((elemento) => elemento.contains(document.activeElement))).toBe(true)
  for (let i = 0; i < 5; i++) {
    await page.keyboard.press('Tab')
    expect(await dialogo.evaluate((elemento) => elemento.contains(document.activeElement))).toBe(true)
  }
  await page.screenshot({ path: 'test-results/galeria-dialogo.png' })
  await page.keyboard.press('Escape')
  await expect(dialogo).not.toBeVisible()
  await expect(abrir).toBeFocused()
  await abrir.click()
  await page.getByRole('button', { name: 'Fechar', exact: true }).click()
  await expect(dialogo).not.toBeVisible()
  await expect(abrir).toBeFocused()
  await abrir.click()
  await page.getByRole('button', { name: 'Descartar e continuar', exact: true }).click()
  await expect(page.locator('#dialogo').getByRole('status')).toBeVisible()
})

test('avisos mostram busca, lista vazia e recuperação de falha no formulário', async ({ page }) => {
  await entrar(page, 'gestor')
  await page.goto('/design')
  const avisos = page.locator('#avisos')
  await avisos.getByRole('button', { name: 'Simular busca', exact: true }).click()
  await expect(avisos.getByText('Buscando empresas…', { exact: true })).toBeVisible()
  await expect(avisos.getByText('1 empresa encontrada', { exact: true })).toBeVisible()
  await avisos.getByRole('button', { name: 'Simular lista vazia', exact: true }).click()
  await expect(avisos.getByText('Nenhum resultado para estes filtros', { exact: true })).toBeVisible()
  await avisos.getByLabel('Anotações do resultado').fill('Minha anotação deve continuar aqui')
  await avisos.getByRole('button', { name: 'Simular falha ao salvar', exact: true }).click()
  await expect(avisos.getByText('Não foi possível salvar', { exact: true })).toBeVisible()
  await avisos.getByRole('button', { name: 'Tentar salvar novamente', exact: true }).click()
  await expect(avisos.getByText('Resultado salvo na demonstração', { exact: true })).toBeVisible()
  await expect(avisos.getByLabel('Anotações do resultado')).toHaveValue('Minha anotação deve continuar aqui')
  await avisos.screenshot({ path: 'test-results/galeria-avisos.png' })
})
