import { expect, test } from '@playwright/test'

test('Fila real separa etapas, preserva notas ao voltar e troca somente após confirmar', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('E-mail').fill('visuale2e@teste.local')
  await page.getByLabel('Senha', { exact: true }).fill('Senha-e2e-2026')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL('/')
  await page.goto('/fila/localizar?cnae=8888888')
  const etapas = page.getByRole('navigation', { name: 'Etapas da prospecção' })
  await expect(etapas.getByRole('link')).toHaveCount(0)
  await expect(etapas.getByRole('button')).toHaveCount(0)
  await page.getByLabel('Tema da Fila').selectOption('light')
  for (const width of [390, 820, 1000, 1280]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.screenshot({ path: 'test-results/fila-puxar.png', fullPage: true })
  await page.getByRole('button', { name: 'Buscar cliente', exact: true }).click()
  await expect(page).toHaveURL(/\/fila\?/)
  await expect(etapas.locator('[aria-current="step"]')).toHaveText('Consultar')
  await expect(etapas.getByRole('button', { name: 'Registrar', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Nota', { exact: true })).toHaveCount(0)
  const empresa = await page.getByRole('heading', { name: /^Visual E2E / }).textContent()
  await page.screenshot({ path: 'test-results/fila-consultar.png', fullPage: true })
  await page.getByRole('button', { name: 'Registrar resultado', exact: true }).click()
  await expect(etapas.locator('[aria-current="step"]')).toHaveText('Registrar')
  await page.getByLabel('Nota', { exact: true }).fill('Rascunho da interface nova')
  await etapas.getByRole('button', { name: 'Consultar', exact: true }).click()
  await page.getByRole('button', { name: 'Registrar resultado', exact: true }).click()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('Rascunho da interface nova')
  await page.getByLabel('Tema da Fila').selectOption('dark')
  for (const width of [820, 1000, 1280]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.screenshot({ path: 'test-results/fila-registrar-escuro.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/fila-registrar-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 800 })
  await etapas.getByRole('button', { name: 'Consultar', exact: true }).click()
  await page.getByRole('button', { name: 'Próxima', exact: true }).click()
  const dialogo = page.getByRole('dialog')
  await expect(dialogo).toBeVisible()
  await dialogo.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page.getByRole('heading', { name: empresa!, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Próxima', exact: true }).click()
  await dialogo.getByRole('button', { name: 'Descartar e continuar', exact: true }).click()
  await expect(page.getByRole('heading', { name: empresa!, exact: true })).not.toBeVisible()
  await expect(etapas.locator('[aria-current="step"]')).toHaveText('Consultar')
  await page.getByRole('button', { name: 'Registrar resultado', exact: true }).click()
  await expect(page.getByLabel('Nota', { exact: true })).toHaveValue('')
})
