import { expect, test } from '@playwright/test'

test('gestor administra usuário em diálogos, combina filtros e mantém foco após desativar', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('E-mail').fill('gestore2e@teste.local')
  await page.getByLabel('Senha', { exact: true }).fill('Senha-e2e-2026')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL('/meu-dia')
  await page.goto('/usuarios')
  await expect(page.locator('nav a[aria-current=page]')).toHaveAttribute('href', '/usuarios')
  const dialogo = page.getByRole('dialog')
  const email = 'visualusuarios@teste.local'
  await page.getByRole('button', { name: 'Novo usuário', exact: true }).click()
  await dialogo.getByLabel('Nome', { exact: true }).fill('Pessoa Visual')
  await dialogo.getByLabel('E-mail', { exact: true }).fill(email)
  await dialogo.getByRole('button', { name: 'Criar usuário', exact: true }).click()
  await expect(dialogo.getByRole('heading', { name: 'Usuário criado' })).toBeVisible()
  await expect(dialogo.locator('code')).not.toBeEmpty()
  await dialogo.getByRole('button', { name: 'Concluir' }).click()
  await expect(page.locator('code')).toHaveCount(0)
  const busca = page.getByLabel('Buscar usuário')
  await busca.fill(email)
  const linha = page.locator('tbody tr')
  await expect(linha).toHaveCount(1)
  await expect(linha).toContainText('Troca pendente')
  await linha.getByRole('button', { name: 'Tornar gestor' }).click()
  await dialogo.getByRole('button', { name: 'Cancelar' }).click()
  await expect(linha.getByRole('button', { name: 'Tornar gestor' })).toBeFocused()
  await linha.getByRole('button', { name: 'Tornar gestor' }).click()
  await dialogo.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(dialogo).toHaveCount(0)
  await expect(linha.getByRole('button', { name: 'Tornar vendedor' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Papel', exact: true }).selectOption('gestor')
  await page.getByRole('combobox', { name: 'Situação', exact: true }).selectOption('ativos')
  await linha.getByRole('button', { name: 'Desativar', exact: true }).click()
  await dialogo.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(dialogo).toHaveCount(0)
  await expect(linha).toHaveCount(0)
  await expect(busca).toBeFocused()
  await expect(page.getByRole('heading', { name: 'Nenhum usuário encontrado' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Situação', exact: true }).selectOption('inativos')
  await expect(linha).toHaveCount(1)
  await linha.getByRole('button', { name: 'Reativar', exact: true }).click()
  await dialogo.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(linha).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Situação', exact: true }).selectOption('ativos')
  await linha.getByRole('button', { name: 'Nova senha provisória' }).click()
  await dialogo.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(dialogo.locator('code')).not.toBeEmpty()
  await dialogo.getByRole('button', { name: 'Concluir' }).click()
  await page.getByRole('button', { name: 'Limpar filtros' }).click()
  for (const largura of [1280, 390]) {
    await page.setViewportSize({ width: largura, height: 900 })
    for (const tema of ['light', 'dark']) {
      await page.getByLabel('Tema de Usuários').selectOption(tema)
      await expect(page.locator('.crm-ui').first()).toHaveAttribute('data-theme', tema)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: `test-results/usuarios-${largura}-${tema}.png`, fullPage: true, animations: 'disabled' })
      await page.getByRole('button', { name: 'Novo usuário', exact: true }).click()
      await expect(dialogo).toBeVisible()
      await page.screenshot({ path: `test-results/usuarios-dialogo-${largura}-${tema}.png`, animations: 'disabled' })
      await dialogo.getByRole('button', { name: 'Cancelar' }).click()
    }
  }
})
